version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: app/src/Dockerfile
    container_name: bpc-backend
    environment:
      - TZ=UTC
    volumes:
      - ./database.db:/app/database.db
      - ./media:/app/media
    expose:
      - '8000'

  bot:
    build:
      context: .
      dockerfile: app/bot/Dockerfile
    container_name: bpc-bot
    environment:
      - API_BASE_URL=http://backend:8000/api
      - BOT_TOKEN=${BOT_TOKEN}
      - MINI_APP_URL=https://${DOMAIN}
      - RANEPASPORT_CHANNEL=${RANEPASPORT_CHANNEL:-@ranepasport}
      - BALBESCREW_CHANNEL=${BALBESCREW_CHANNEL:-@balbescrew}
      - BDEV_CHANNEL=${BDEV_CHANNEL:-@bdevbync}
    depends_on:
      - backend

  nginx:
    build:
      context: .
      dockerfile: deploy/nginx.Dockerfile
      args:
        - VITE_API_URL=/api
    container_name: bpc-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.ssl.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: bpc-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes: {}
